sudo: required
language: generic

notifications:
  email: false

branches:
  only:
    - master

services:
  - docker

script:
  - docker-compose build
  - docker-compose run --rm --name web web bundle exec rspec
